baseURL = "https://qaqAdrian.github.io"
title = "一个非常愁起名字的人"
theme = "m10c"
paginate = 5
# publishdir = "../"
buildDrafts = false
googleAnalytics = "G-9QL623VTYK"
# disqusShortname = "qaqadrian"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Adrian"
  description = "如果需要联系，可以发送至邮箱yahaha7777@gmail.com"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/qaqadrian"
    icon = "avatar.jpg"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  [params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
   lightestColor = "#e0e0e0"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
