
baseurl = "https://qaqadrian.github.io"
languageCode = "zh"
title = "一个为起名字很愁恼的人的博客"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/QaQAdrian\">QaQAdrian</a> 2019"
# disqusShortname = "shortname"
# googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
publishDir = ".."


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Hello" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

# [params.features]
# disqusOnDemand = true  # Load Disqus comments on click

[params.social]
github = "QaQAdrian"
email = "yahaha7777@gmail.com"

[params.social.config]
platforms = ["github","email"]

# [params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

# [blackfriday]
# hrefTargetBlank = true